### ISSUE TITLE
No bloco, listar os oferecimento em um select e buscável - assim temos tamanho fixo

### ISSUE THREAD

**Issue by thiagogomesverissimo** [moodle-usp/moodle-block_extensao#12]

**Comment by Potalej** [comment]
Implementei um <select> buscável utilizando o "autocomplete do Moodle Forms:
https://docs.moodle.org/dev/lib/formslib.php_Form_Definition#autocomplete

Adicionei alguns tratamentos de erros, resta ainda ver se são suficientes.
