### ISSUE TITLE
Mandar o email para todos ministrantes que foram inseridos

### ISSUE THREAD

**Issue by thiagogomesverissimo** [moodle-usp/moodle-block_extensao#16]
Incluir informações sobre ambiente criado (curso e oferecimento), quem o criou, data que o ambiente foi criado. Tirar informações da senha, pois será usado somente shibboleth.

**Comment by TalitaVentura16** [comment]
O e-mail de confirmação de matrícula do professor no curso foi adicionado e corrigido, agora ele informa a data de criação, nome do curso, turma, e o ministrante que criou o ambiente virtual. Nesse sentido, o e-mail também informa o papel de ministrante a ele atribuído.
