### ISSUE TITLE
Dar a opção dos "Gerente da categoria" criar os ambientes pelo plugin

### ISSUE THREAD

**Issue by thiagogomesverissimo** [moodle-usp/moodle-block_extensao#18]

**Comment by TalitaVentura16** [comment]
Na visualização do bloco do plugin extensão: 
Antes da verificação se o usuário logado é ministrante, verificar se ele é gerente de alguma categoria;
Caso sim:
	capturar os cursos da categoria, listar no select da página inicial;
Caso não:
	manter como está;

**Comment by Potalej** [comment]
Para capturar as categorias em que um usuário é gerente estou fazendo o seguinte processo:
1. Dado o id do usuário logado, verifico se tem registros na tabela `mdl_role_assignments` com `userid` correspondente e com `roleid = 1` (role de MANAGER);
2. Se tiver algum registro, vai na tabela `mdl_context` verificar se o `$role->contextid$` tem `contextlevel = 40` (COURSECAT);
3. Se for COURSECAT, então vai na tabela `mdl_course_categories` e captura informações básicas da categoria.

O próximo passo é fazer as modificações na tabela "mdl_block_extensao_turma" e em seguida fazer a busca.

**Comment by Potalej** [comment]
Listagem de cursos quando o usuário logado é gerente de alguma categoria.
A busca é feita pelo `idnumber` da categoria, precisamos ver isso.
A criação do ambiente possivelmente não está funcionando, pois o usuário gerente não é incluído. Resta fazer isso e o acima então.

**Comment by Potalej** [comment]
No commit 1a014081245204e1b2a99679c54120fcd05e8ce9, adicionei o `idnumber` na criação das categorias. Agora em sua criação o `idnumber` é definido em correspondência ao "codcam" (no caso dos campi) ou ao "codund" no caso das unidades.
No Moodle Extensão isso provavelmente já está definido assim. Se não estiver, então temos um problema.

**Comment by Potalej** [comment]
No commit f9ce059 fiz as adições que faltavam para permitir que um gerente de categoria crie cursos de sua categoria e subcategorias, que era basicamente o que faltava. Agora o gerente é inscrito na turma como "editingteacher", como os outros.

Surgiu, porém, outra dúvida: todos os usuários que são gerentes das categorias que contemplam o curso deveriam ser automaticamente inscritos também? Ou um usuário que é gerente de categoria já pode editar qualquer curso?
