### ISSUE TITLE
Versão do plugin sem composer

### ISSUE THREAD

**Issue by ewout** [moodle-usp/moodle-block_extensao#30]
A minha instalação de desenvolvimento está com uma versão do composer quebrado. 

Vocês tem como criar uma versão deste plugin que não depende do composer? Do jeito que está, a instalação do plugin termina com erro:
```
Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='/var/dados/html/extensao/lib/pear:.:/usr/share/php') in /var/dados/html/extensao/blocks/extensao/blo
ck_extensao.php on line 16
```

Entendo que boas práticas de desenvolvimento PHP podem exigir composer, mas para falar verdade, nunca vi plugin do Moodle exigir um passo de instalação que inclui composer. Eventuais bibliotecas vendor já vem juntos.

**Comment by Potalej** [comment]
Composer removido.
