### ISSUE TITLE
Erro ao criar bloco por usuário comum

### ISSUE THREAD

**Issue by ewout** [moodle-usp/moodle-block_extensao#31]
Instalei o plugin, criei um block como gerente, tudo ok. Mas criando o bloco com uma conta com username = `docente` e idnumber = vazio (não setado) dá esse erro:

```
Debug info: Unknown column 'HU' in 'where clause'
SELECT codofeatvceu FROM mdl_block_extensao_turma WHERE codcam = HU OR codund = HU
```

**Comment by Potalej** [comment]
O erro surgiu no "pages/criar_ambiente.php", quando se captura as categorias as quais o usuário logado é gerente e se busca por cursos cujo `codcam` ou `codund` seja igual ao idnumber da categoria.

O problema estava na query de buscar na função `categoria_turmas`, que esperava procurar somente inteiros e recebeu uma string. O mesmo erro poderia aparecer em outras funções, então já adicionei o tratamento de erro nos casos.
