### ISSUE TITLE
Como escolher e-mails?

### ISSUE THREAD

**Issue by Potalej** [moodle-usp/moodle-block_extensao#40]
Na base da USP temos uma tabela "EMAILPESSOA", que associa usuários a endereços de e-mail, possibilitando que um mesmo usuário tenha diversos e-mails. Atualmente, quando vamos capturar o e-mail de um usuário, pegamos o primeiro que aparecer. O problema é que pode ser que escolhamos um e-mail que não seja mais utilizado pelo usuário, ou que seja um secundário, e no caso do Moodle isso pode prejudicar os prazos.

Assim, precisamos procurar por e-mails principais. A tabela tem a coluna "stamtr", que indica se o e-mail é o principal ou não, então poderia ser utilizada. No entanto, Ewout atestou que pode haver incongruências quanto aos dados dessa coluna, e ficou de confirmar se procede.

Se não pudermos utilizar a coluna `stamtr`, precisaremos de outra forma de verificar. Nesse caso, faria sentido uma busca por "@usp.br" ou por "@INSTITUTO.usp.br". Qual o melhor jeito de fazer isso?

**Comment by TalitaVentura16** [comment]
Na busca por email o campo 'stamtr' deve conter a marcação 'S' para ser a o e-mail principal para o envio de informações.
