### ISSUE TITLE
Cursos com várias turmas

### ISSUE THREAD

**Issue by Potalej** [moodle-usp/moodle-block_extensao#41]
Alguns cursos possuem várias turmas com os mesmos nomes. Se um usuário é docente de várias dessas turmas, fica difícil identificar qual turma é qual na hora de criar o ambiente. Foi indicado que toda turma tem um número sequencial que indica seu oferecimento, então poderíamos capturar esse número para facilitar a vida do docente.

Para começar, onde está esse número?

**Comment by ewout** [comment]
Acho que é `numseqofeedi` da tabela OFERECIMENTOATIVIDADECEU

**Comment by Potalej** [comment]
Podemos adicionar a data de início na seleção de curso `dtainiofeatv` (ano/mês), para facilitar a visualização do docente.
Será necessário adicionar um campo na tabela `block_extensao_turma`.
