### ISSUE TITLE
Opções no script sync.php

### ISSUE THREAD

**Issue by ewout** [moodle-usp/moodle-block_extensao#45]
Rodar
```
sync.php --pular_ministrantes
```
deixe a tabela mdl_block_extensao_ministrante vazio? Isso me parece comportamento inesperado. Não deveria deixar esta tabela do jeito que está?  Ou, se é isso mesmo, renomear a opção "limpar_ministrantes". Mas, porque alguém faria isso?

Pensando bem, qual é caso de uso desta opção? Precisamos repensar as opções deste script?

**Comment by Potalej** [comment]
Refatorei o script de sincronização e implementei a seguinte solução para o problema apresentado:

- Quando a opção "--pular_ministrantes" não for passada, todas as turmas e ministrantes que não tiverem um ambiente Moodle associado serão removidos da base e reinseridos em seguida;
- Quando a opção for passada, todas as turmas sem ambiente Moodle ainda serão removidas, mas seus ministrantes permanecerão na base e novos ministrantes não serão adicionados. As turmas serão então reinseridas, e se houver turmas novas estas terão seus ministrantes adicionados normalmente.

O propósito da solução é permitir a escolha de sincronizar os ministrantes com o Apolo ou não. A diferença aparece no caso de se adicionar ou remover um ministrante de uma turma no Apolo após já ter sido feita uma sincronização com a base da Extensão.
