### ISSUE TITLE
Quando um ministrante não tem email nas tabelas replicadas, não criar usuário no moodle e nem mandar email (notificar que conta não foi criada)

### ISSUE THREAD

**Issue by thiagogomesverissimo** [moodle-usp/moodle-block_extensao#6]
Caso de um usuário sem email cadastrado: Sergio Soriano [Especialista]
Curso: MBA em Agronegócios (2025) 
codofeatvceu: 99279

**Comment by TalitaVentura16** [comment]
Adicionei um tratamento de erros, se o professor não possuir um e-mail no sistema o cadastro não é realizado, e uma mensagem de erro aparece informando seu nome, e que este não possui e-mail valido.

**Comment by TalitaVentura16** [comment]
O erro anterior foi corrigido, caso o professor não possua um e-mail uma mensagem de erro aparece e solicita o suporte.
