### ISSUE TITLE
Interface de busca

### ISSUE THREAD

**Issue by ewout** [moodle-usp/moodle-block_extensao#72]
Na minha instância há um problema de encoding... problema só na minha base?

Há um problema de layout também, que oculta a "setinha para baixo" do widget de busca, que mostraria todos as opções.

![image](https://github.com/moodle-usp/moodle-block_extensao/assets/6329/591f5e0d-4179-4158-85d0-656eae8d5099)

**Comment by Potalej** [comment]
O encoding foi resolvido, a função `utf8_encode` foi descontinuada, então precisamos substituir pela função `mb_convert_encoding`.

A questão da interface é um problema. Ainda não sei se há forma de resolver sem um CSS externo.
