### ISSUE TITLE
Criar uma Task Moodle para chamar o cli/sync.php

### ISSUE THREAD

**Issue by thiagogomesverissimo** [moodle-usp/moodle-block_extensao#9]

**Comment by Potalej** [comment]
Schedule task criada, depende do Cron rodar (se não ficar travada como ASAP). Para rodar o cron manualmente (na raiz do Moodle):
```
php admin/cli/cron.php
```

**Comment by Potalej** [comment]
Schedule task criada, depende do Cron rodar (se não ficar travada como ASAP). Para rodar o cron manualmente (na raiz do Moodle):
```
php admin/cli/cron.php
```
